pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git 'https://github.com/faizan5zanahmad/devsecop_tetris.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t tetris .'
            }
        }

        stage('List Docker Images') {
            steps {
                sh 'docker images'
            }
        }

    }
}

